### ISSUE TITLE
Maven publishing

### ISSUE THREAD

**Issue by paride** [microg/android_external_GmsLib#10]
Is there any plan to publish this library to maven? I understand it isn't complete yet, but I think the option to give it a try with just a `sed` regexp would give the project a nice boost. Thanks!

**Comment by mar-v-in** [comment]
Snapshots are pushed to Sonatype snapshot repo. You can use sth like `repositories { maven { url 'https://oss.sonatype.org/content/repositories/snapshots' } }` in your `build.gradle` to use the repo. You will be able to use the `sed` statement given in the README afterwards.

I am pretty sure there will be a first testing "release" pushed to maven central within the next months.

**Comment by ale5000-git** [comment]
I'm closing this issue since there is a discussion about merging the repo and upload to maven [here](https://github.com/microg/android_packages_apps_GmsCore/issues/859).
