### ISSUE TITLE
App: MAPS.ME

### ISSUE THREAD

**Issue by relan** [microg/android_external_GmsLib#2]
I'm trying to liberate [MAPS.ME](https://github.com/relan/omim/tree/libre-5.1.6) from proprietary dependencies. Your GmsLib looks to be a very promising way to do this. I've faced a several issues though (all happen while I compile MAPS.ME).

1) Gradle is unable to find `org.microg.gms:play-services:1.0-SNAPSHOT`. Looks like GmsLib group prefix is incorrect. Fixed with

``` patch
diff --git a/build.gradle b/build.gradle
index 49dfafa..30e4b27 100644
--- a/build.gradle
+++ b/build.gradle
@@ -16,6 +16,6 @@

 // Top-level build file where you can add configuration options common to all sub-projects/modules.
 subprojects {
-    group = 'org.microg'
+    group = 'org.microg.gms'
     version = '1.0-SNAPSHOT'
 }
```

2) Gradle complains about duplicate packages `org.microg.gms.wearable`. I think play-services-cast package name is wrong. Fixed with

``` patch
diff --git a/play-services-cast/src/main/AndroidManifest.xml b/play-services-cast/src/main/AndroidManifest.xml
index bb22a33..2031102 100644
--- a/play-services-cast/src/main/AndroidManifest.xml
+++ b/play-services-cast/src/main/AndroidManifest.xml
@@ -16,7 +16,7 @@
   -->

 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
-    package="org.microg.gms.wearable">
+    package="org.microg.gms.cast">

     <uses-sdk android:minSdkVersion="9" />

```

3) GoogleApiAvailability class is missing:

```
/home/xxx/omim/android/src/com/mapswithme/maps/location/LocationHelper.java:19: error: cannot find symbol
import com.google.android.gms.common.GoogleApiAvailability;
                                    ^
  symbol:   class GoogleApiAvailability
  location: package com.google.android.gms.common
```

Documentation says GooglePlayServicesUtil is deprecated, GoogleApiAvailability should be used instead. There will be more and more app that require it. Please consider adding this class.

Thanks for your efforts!
##

**Comment by ale5000-git** [comment]
@mar-v-in: Any update on this?

**Comment by rugk** [comment]
There is a Maps.me fork at https://gitlab.com/axet/omim, where this may be suited for. (I think currently this is removed.)

I've asked about this lib, here: https://gitlab.com/axet/omim/issues/69

**Comment by mar-v-in** [comment]
1. Group should be `org.microg`, is there still a reference to `org.microg.gms` somewhere?
2. Was already fixed in 276288751397b63730bdb220d129eabb7ffca2d3
3. `GoogleApiAvailability` is there now :)

**Comment by ale5000-git** [comment]
@relan: Could you please retry with the latest code?

**Comment by relan** [comment]
> @relan: Could you please retry with the latest code?

I've lost interest in MAPS.ME long ago, sorry.
