### ISSUE TITLE
Adding GCM

### ISSUE THREAD

**Issue by mimi89999** [microg/android_external_GmsLib#3]
@mar-v-in Are there any plans to include GCM support in this library?

**Comment by mar-v-in** [comment]
Yes. I already started development but had no time to get it to a usable state. I will try to provide a somewhat useful state the next days (which should be enough to get basic push notifications running).

**Comment by mimi89999** [comment]
If you already have written some code, could you push it to a dev branch?

**Comment by mar-v-in** [comment]
I don't know what exactly is in the code I wrote (it's some time ago already I worked on that), so I first have to look through it, but I'll for sure push something the next days.

**Comment by mar-v-in** [comment]
A first working (but likely incomplete) version is in git as of 3bb89224dc28fddce7049e3e693c320e79514318

**Comment by mario** [comment]
@mar-v-in did push ever start working? Can't get it to work atm :-/
