### ISSUE TITLE
Publish artifacts to central/jcenter/sonatype

### ISSUE THREAD

**Issue by krt16s** [microg/android_external_GmsLib#4]
It would ease up integration (or even testing) when artefacts would be available from well known repositories, like central, jcenter or sonatype.

Jitpack (https://jitpack.io/#microg/android_external_GmsLib/) wrongly advertised it as being build, but it wasn’t, and frankly I don’t like how they do not honour naming (and not opening up their build system). I found an old and crufty play-services-api version at sonatype (https://oss.sonatype.org/content/repositories/snapshots/org/microg/) but I havent even bother trying that.

**Comment by mar-v-in** [comment]
I pushed a snapshot from the current master to https://oss.sonatype.org/content/repositories/snapshots/org/microg/
Releases will go into maven central.
