### ISSUE TITLE
Can't Add Missing Permission

### ISSUE THREAD

**Issue by landry314** [microg/android_external_GmsLib#6]
The Permission missing alert is sitting there in the microG Settings but REQUEST MISSING PERMISSIONS does nothing and in the Self-Check as well under Permission to read phone status where it says "Touch here to grant...", it also does nothing...

I need to enable this permission but I already denied it before and now it won't let me change my mind... I am thinking i have to uninstall and reinstall from the f-droid repository.

I am using Version 0.2.4-50-g6766fa4 on Cyanogenmod 13 while eagerly awaiting the release version.

**Comment by landry314** [comment]
i hope this is the right github page to post this.

**Comment by mar-v-in** [comment]
It's not the right point (that would be the GmsCore repo), but you should be able to grant the permissions as well through the System Settings -> Apps -> Gear Icon -> App permissions

**Comment by landry314** [comment]
yes, this worked, thank you.
